spring:
  application:
    name: zuul-server

server:
  port: 8500
zuul:
  routes:
    user-server:
      path: /user-server/**
      serviceId: user-server
    user-client:
      path: /user-client/**
      serviceId: user-client
    order-server:
      path: /order-server/**
      serviceId: order-server
    order-client:
      path: /order/client/**
      serviceId: order-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
