server:
  port: 9001
spring:
  application:
    name: config-server
  profiles:
      active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:E:/springcloud/myspringcloud/config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
management:
  security:
    enabled: false
